-  name: 应用配方
   base_url: ${get_base_url(cms_url)}
   request:
      url: /api/v1/runtimeformula/${get_extract_data(formula_id)}/apply
      method: post
      headers:
         X-Project: ${get_extract_data(x_project)}
         Authorization: Bearer ${get_extract_data(Authorization)}
   validate:
      -  equals: {status_code: 200}